server:
  port: 8190

##DB properties
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rempms_document
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: "file:C:/P-DEV/BE/rempms-document-service/src/main/resources/template/"

# ========================= locations ==========================
document:
  base:
    file:
      path: C:\document-data\
    font:
      path: "C:/P-DEV/BE/rempms-document-service/src/main/resources/fonts/TheSansSemiLight Plain.ttf"
  max:
    image: 4000000
    document: 50000000