version: "3.2"

services:
#  Service
  app:
    build: .
    ports:
      - "8189:8189"
    networks:
      - p-dev-shared-network
    environment:
      - CONSUL_HOST=p-dev-consul:8500   # Link your app to the running Consul container
      - POSTGRES_HOST=p-dev-postgres    # Link your app to the running PostgreSQL container
      - POSTGRES_USER=maleeshasa
      - POSTGRES_PASSWORD=300400@AzIT
      - POSTGRES_DB=rempms_recruitment

# Shared network
networks:
  p-dev-shared-network:
    external: true   # Use the already existing shared network (not created by Compose)

# Volumes (unchanged)
volumes:
  p-dev-data-volume:
    external: true   # Use the existing volume if you're using one for PostgreSQL


# Consul agent
#  consul:
#    image: hashicorp/consul:latest
#    container_name: p-dev-consul
#    ports:
#      - "8500:8500"
#    networks:
#      - p-dev-shared-network

# Database
#  postgres:
#    image: bitnami/postgresql:latest
#    container_name: p-dev-postgres
#    environment:
#      POSTGRES_USER: maleeshasa
#      POSTGRES_PASSWORD: 300400@AzIT
#      POSTGRES_DB: rempms_recruitment
#    ports:
#      - "5432:5432"
#    networks:
#      - p-dev-shared-network
#    volumes:
#      - p-dev-data-volume:/var/lib/postgresql/data
