server:
  port: 8189

##DB properties
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rempms_recruitment
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
