server:
  port: 8081

profiles:
  active: prod

spring:
  application:
    name: rempms-api-gateway-service
  main:
    web-application-type: reactive
  cloud:
    consul:
      discovery:
        register: true
        prefer-ip-address: true
    gateway:
      routes:
        - id: rempms-location-service
          uri: lb://rempms-location-service  # Replace with actual service port
          predicates:
            - Path=/api/location/**

        - id: rempms-communication-service
          uri: lb://rempms-communication-service  # Replace with actual service port
          predicates:
            - Path=/api/communication/**

        - id: rempms-recruitment-service
          uri: lb://rempms-recruitment-service  # Replace with actual service port
          predicates:
            - Path=/api/recruitment/**

        - id: rempms-candidate-service
          uri: lb://rempms-candidate-service  # Replace with actual service port
          predicates:
            - Path=/api/candidate/**

        - id: rempms-document-service
          uri: lb://rempms-document-service  # Replace with actual service port
          predicates:
            - Path=/api/document/**

        - id: rempms-draft-service
          uri: lb://rempms-draft-service  # Replace with actual service port
          predicates:
            - Path=/api/draft/**