server:
  port: 8186

##DB properties
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rempms_admin
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

# =========================File locations ==========================
document:
  max:
    image: 4000000
    document: 50000000
  userImage: "H:/REMPMS-Project/Documents/userImage"
  jobPostImage: "H:/REMPMS-Project/Documents/postImage"
  cv: "H:/REMPMS-Project/Documents/cv"
